### ISSUE TITLE
Default styling for pagination

### ISSUE THREAD

**Issue by codenameEli** [launchdm/rocket#9]
Propose an additional stylesheet in our defaults for styling of the pagination links. This is just a starting point. If anyone opposes please comment.

``` CSS
.pagination {

    ul {
        display: table;
        margin: 5px auto;
        padding: 0;
    }

    li {
        display: inline-block;
        padding: 7px 10px;
        margin-right: 3px;
    }
}
```
